"use client";

import { motion } from "framer-motion";
import { Ban, ArrowRight, DollarSign, LayoutDashboard, ScanSearch, ShieldCheck, SlidersHorizontal, Tags } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import FAQ, { type FaqItem } from "@/components/FAQ";

const allocation = [
  ["Every Resource, Tagged or Not", "Zolix's zero-agent detection engine allocates spend to a team, project, or environment based on actual usage signals, not a manually applied tag. A resource that was never labeled still shows up correctly attributed, from the first day it's connected.", ScanSearch],
  ["No Tagging Cleanup Project Required", "There's no prerequisite phase where your team has to retroactively tag every resource before the dashboard becomes trustworthy. Zolix works with your environment as it exists today, including the parts that have drifted out of tagging compliance over the past year or two.", Ban],
  ["A Flexible Allocation Dimension, Not a Rigid Schema", "Cost can be sliced by team, product, customer, feature, or environment - whichever dimension actually matters for a given conversation - instead of being locked into whatever tagging schema was decided on eighteen months ago and never fully enforced.", SlidersHorizontal],
] as const;

function Button({ href, children, light = false }: { href: string; children: ReactNode; light?: boolean }) {
  const className = `group inline-flex items-center gap-3 rounded-full px-7 py-4 text-[10px] font-bold uppercase tracking-[0.18em] transition-colors ${light ? "bg-white text-zolix-dark hover:bg-zolix-orange hover:text-white" : "bg-zolix-dark text-white hover:bg-zolix-orange"}`;
  const content = <>{children}<ArrowRight size={15} strokeWidth={3} className="transition-transform duration-200 group-hover:translate-x-1" /></>;
  return href.startsWith("http") ? <a href={href} target="_blank" rel="noreferrer" className={className}>{content}</a> : <Link href={href} className={className}>{content}</Link>;
}

const reveal = { initial: { opacity: 0, y: 16 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.18 } };

export default function CloudCostManagementSoftware({ faqs, breadcrumbs }: { faqs: FaqItem[]; breadcrumbs: ReactNode }) {
  return <>
    <section data-nav-theme="beige" className="relative overflow-hidden bg-zolix-beige px-6 pb-20 pt-40 md:pb-28">
      <div className="absolute -right-24 top-10 h-[34rem] w-[34rem] rounded-full border border-zolix-orange/15" />
      <div className="absolute right-32 top-48 h-60 w-60 rounded-full bg-zolix-orange/15 blur-3xl" />
      <div className="relative mx-auto max-w-7xl">
        {breadcrumbs}
        <div className="grid gap-14 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
          <div>
            <motion.p initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="mb-7 text-[10px] font-bold uppercase tracking-[0.22em] text-zolix-orange">Technology / Cloud Cost Management Software</motion.p>
            <motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.55 }} className="max-w-3xl text-4xl font-extrabold leading-[.98] tracking-[-0.05em] text-zolix-dark md:text-6xl">Cloud Cost Management Software Built for How Your Infrastructure Actually Looks</motion.h1>
            <motion.p initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.12 }} className="mt-8 max-w-2xl text-lg font-medium leading-relaxed text-zolix-dark/60 md:text-xl">Most cost management software works great - as long as every resource is tagged perfectly. Zolix is built for the environment you actually have: untagged resources, shared infrastructure, and cost that doesn&apos;t map cleanly to a single owner. See your dashboard from day one, not after a six-month tagging cleanup project.</motion.p>
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="mt-10 flex flex-wrap gap-4"><Button href="/demo">Book a Demo</Button></motion.div>
          </div>
          <motion.div initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.65, delay: 0.1 }} className="relative mx-auto w-full max-w-lg rounded-[2rem] border border-zolix-dark/10 bg-white/70 p-6 shadow-[0_24px_70px_rgba(26,26,26,0.08)] backdrop-blur-sm md:p-8">
            <div className="flex items-center justify-between border-b border-zolix-dark/10 pb-5 text-[9px] font-bold uppercase tracking-[0.18em]"><span className="text-zolix-dark/45">Allocation without tags</span><span className="flex items-center gap-2 text-zolix-orange"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-zolix-orange" />100%</span></div>
            <div className="mt-7 space-y-3">
              {[["Tagged resources", "Allocated as usual", Tags], ["Untagged resources", "Allocated by usage signal", ScanSearch], ["Untaggable resources", "Allocated automatically", LayoutDashboard]].map(([title, label, Icon], index) => {
                const NodeIcon = Icon as typeof Tags;
                return <motion.div key={title as string} initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.32 + index * 0.1 }} className="relative flex items-center gap-4 rounded-2xl bg-zolix-beige/70 p-4"><span className="relative z-10 grid h-7 w-7 place-items-center rounded-full bg-zolix-dark text-white"><NodeIcon size={13} /></span><div><p className="text-sm font-bold text-zolix-dark">{title as string}</p><p className="mt-0.5 text-xs font-medium text-zolix-dark/45">{label as string}</p></div><span className="ml-auto text-[9px] font-bold uppercase tracking-wider text-zolix-orange">Allocated</span></motion.div>;
              })}
            </div>
            <p className="mt-7 border-t border-zolix-dark/10 pt-5 text-sm font-medium leading-relaxed text-zolix-dark/50">Tagging coverage rarely gets past 60-70% - Zolix allocates 100% of spend regardless.</p>
          </motion.div>
        </div>
      </div>
    </section>

    <section data-nav-theme="light" className="bg-white px-6 py-24 md:py-32"><div className="mx-auto max-w-5xl"><p className="mb-5 text-[10px] font-bold uppercase tracking-[0.22em] text-zolix-orange">The Problem With &quot;Just Tag Everything&quot;</p><p className="text-2xl font-medium leading-relaxed tracking-tight text-zolix-dark md:text-3xl">Every cost management tool tells you to tag your resources properly, and every team means to. In practice, tagging coverage rarely gets past 60 to 70% before drift sets in - a new resource gets spun up without a tag, an old one loses its label during a migration, and a chunk of spend quietly becomes unattributable. The result is a dashboard with a large &quot;untagged&quot; bucket that nobody can explain.</p><p className="mt-8 text-lg font-medium leading-relaxed text-zolix-dark/55">Zolix doesn&apos;t require tagging coverage to be complete before it becomes useful. It allocates 100% of spend - tagged, untagged, and effectively untaggable - using a detection model that reads usage patterns directly, rather than relying on a label someone had to remember to apply.</p></div></section>

    <section data-nav-theme="beige" className="bg-zolix-beige px-6 py-24 md:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-2 lg:items-start"><div><p className="mb-5 text-[10px] font-bold uppercase tracking-[0.22em] text-zolix-orange">Allocation That Doesn&apos;t Depend on Tags</p><h2 className="text-4xl font-bold leading-[1.05] tracking-[-0.05em] text-zolix-dark md:text-6xl">100% allocation, no cleanup required</h2><p className="mt-6 max-w-xl text-lg font-medium leading-relaxed text-zolix-dark/55">See every cost in the right business context, including the resources that incomplete tagging would otherwise leave behind.</p><div className="mt-8"><Button href="/demo">Book a Demo</Button></div></div><motion.div {...reveal} className="relative min-h-[26rem] overflow-hidden rounded-2xl bg-zolix-dark shadow-[0_18px_45px_rgba(155,85,0,.16)]"><Image src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1400&q=85" alt="Analytics dashboard representing cloud cost management software" fill sizes="(min-width: 1024px) 45vw, 100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-zolix-dark/90 via-zolix-dark/35 to-transparent" /><div className="absolute inset-x-5 bottom-5 flex items-end justify-between"><span className="rounded-full border border-white/20 bg-zolix-dark/55 px-3 py-2 text-[9px] font-bold uppercase tracking-[.16em] text-white backdrop-blur-md">Cost management intelligence</span><a href="https://unsplash.com/license" target="_blank" rel="noreferrer" className="text-[7px] font-medium text-white/60 underline-offset-2 hover:text-white hover:underline">Photo licensed via Unsplash</a></div></motion.div></div><div className="mt-20 grid gap-x-14 gap-y-2 md:mt-28 md:grid-cols-3">{allocation.map(([title, desc, Icon], index) => <motion.article key={title} {...reveal} transition={{ delay: index * 0.06 }} className="group flex items-start gap-5 rounded-2xl px-4 py-8 transition-all duration-300 hover:bg-white/70"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-white text-zolix-orange transition-transform duration-300 group-hover:-translate-y-0.5"><Icon size={21} /></span><div className="flex-1"><h3 className="text-xl font-bold tracking-tight text-zolix-dark">{title}</h3><p className="mt-4 text-[15px] font-medium leading-relaxed text-zolix-dark/55">{desc}</p></div></motion.article>)}</div><div className="mt-16 rounded-3xl bg-zolix-dark px-8 py-14 text-center text-white md:px-16 md:py-16"><h3 className="text-3xl font-bold leading-none tracking-[-0.05em] md:text-5xl">Ready for 100% Cost Allocation, No Cleanup Required?</h3><div className="mt-8 flex flex-wrap justify-center gap-4"><Button href="/demo" light>See the Dashboard</Button><Button href="/demo" light>Book a Demo</Button></div></div></div></section>

    <section data-nav-theme="light" className="bg-white px-6 py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 md:grid-cols-2"><div><span className="grid h-11 w-11 place-items-center rounded-xl bg-zolix-beige text-zolix-orange"><DollarSign size={21} /></span><h2 className="mt-6 text-3xl font-bold leading-none tracking-[-0.04em] text-zolix-dark md:text-4xl">Cost Numbers That Mean Something to the Business</h2><p className="mt-5 text-[15px] font-medium leading-relaxed text-zolix-dark/55">A dashboard full of dollar figures doesn&apos;t tell anyone whether spend is reasonable. Zolix connects cost to the business context around it - so a number like &quot;$40,000 this month&quot; becomes &quot;$40,000 to support a feature generating $310,000 in attributable revenue,&quot; the version of that number a leader can actually act on.</p></div><div><span className="grid h-11 w-11 place-items-center rounded-xl bg-zolix-beige text-zolix-orange"><LayoutDashboard size={21} /></span><h2 className="mt-6 text-3xl font-bold leading-none tracking-[-0.04em] text-zolix-dark md:text-4xl">Software, Not Just a Service</h2><p className="mt-5 text-[15px] font-medium leading-relaxed text-zolix-dark/55">Zolix is a self-serve platform with a live dashboard your team logs into directly - not a manual audit delivered as a PDF once a quarter, and not a consulting engagement that requires a services contract to get started. Connect your cloud accounts through read-only access, and the dashboard is live from day one.</p></div></div></section>

    <section data-nav-theme="dark" className="bg-zolix-dark px-6 py-20 text-white md:py-24"><div className="mx-auto max-w-7xl"><p className="mb-10 text-[10px] font-bold uppercase tracking-[0.22em] text-zolix-orange">What teams see on day one</p><div className="grid gap-10 border-t border-white/15 pt-9 md:grid-cols-3"><div><p className="text-3xl font-extrabold tracking-[-0.06em] text-zolix-orange md:text-4xl">100% Allocation</p><p className="mt-4 text-sm font-medium leading-relaxed text-white/60">Coverage - every dollar of spend attributed, including untagged and effectively untaggable resources.</p></div><div><p className="text-3xl font-extrabold tracking-[-0.06em] text-zolix-orange md:text-4xl">24 Hours</p><p className="mt-4 text-sm font-medium leading-relaxed text-white/60">to a fully populated dashboard after connecting your first cloud account.</p></div><div><p className="text-3xl font-extrabold tracking-[-0.06em] text-zolix-orange md:text-4xl">Zero Tagging</p><p className="mt-4 text-sm font-medium leading-relaxed text-white/60">Prerequisite - no cleanup project, no enforcement campaign, no waiting period before the data is trustworthy.</p></div></div></div></section>

    <FAQ items={faqs} theme="beige" />

    <section data-nav-theme="dark" className="bg-zolix-dark px-6 py-20 text-white md:py-28"><div className="mx-auto max-w-5xl text-center"><ShieldCheck size={28} className="mx-auto text-zolix-orange" /><h2 className="mt-8 text-4xl font-bold leading-none tracking-[-0.05em] md:text-6xl">Stop Waiting on a Tagging Project to See Your Real Cloud Costs</h2><p className="mx-auto mt-7 max-w-2xl text-lg font-medium leading-relaxed text-white/60">Connect your accounts through read-only access and get a fully attributed dashboard - tagged and untagged spend included - from day one.</p><div className="mt-10 flex flex-wrap justify-center gap-4"><Button href="/demo" light>See the Dashboard</Button><Button href="/demo" light>Book a Demo</Button></div></div></section>
  </>;
}
